# Generated by Django 4.2.7 on 2023-12-02 17:30

import apps.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.FileField(upload_to='website/')),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[apps.core.utils.validators.validate_email])),
                ('tel_number', models.IntegerField()),
                ('twitter_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
