# Generated by Django 4.2.7 on 2023-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_websiteinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
