# Generated by Django 4.2.7 on 2023-12-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_websiteinformation_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinformation',
            name='tel_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
