# Generated by Django 4.2.7 on 2023-12-03 08:33

import apps.core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_websiteinformation_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinformation',
            name='email',
            field=models.EmailField(max_length=254, validators=[apps.core.utils.validators.validate_email]),
        ),
    ]
