# Generated by Django 4.2.7 on 2023-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='website_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
